<!DOCTYPE html>
<html class="ls-theme-light-blue">
  <head>
    <title>Banco de Dados - Limpeza - Gescom</title>

    <meta charset="utf-8">
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta name="description" content="Insira aqui a descrição da página.">
    <link href="http://assets.locaweb.com.br/locastyle/3.10.0/stylesheets/locastyle.css" rel="stylesheet" type="text/css">
    <link rel="icon" sizes="192x192" href="/locawebstyle/assets/images/ico-boilerplate.png">
    <link rel="apple-touch-icon" href="/locawebstyle/assets/images/ico-boilerplate.png">
  </head>
  <body>
    <div class="ls-topbar ">

  <!-- Barra de Notificações -->
  <div class="ls-notification-topbar">

    <!-- Links de apoio -->
    <div class="ls-alerts-list">
      <a href="#" class="ls-ico-bell-o" data-counter="8" data-ls-module="topbarCurtain" data-target="#ls-notification-curtain"><span>Notificações</span></a>
    </div>

    <!-- Dropdown com detalhes da conta de usuário -->
    <div data-ls-module="dropdown" class="ls-dropdown ls-user-account">
      <a href="#" class="ls-ico-user">
        <img src="/locawebstyle/assets/images/locastyle/avatar-example.jpg" alt="" />
        <span class="ls-name"><?php echo $user['usuario'] ?></span>
      </a>

      <nav class="ls-dropdown-nav ls-user-menu">
        <ul>
          <li><a href="/login/finalizar">Sair</a></li>
         </ul>
      </nav>
    </div>
  </div>

  <span class="ls-show-sidebar ls-ico-menu"></span>

  <a href="/"  class="ls-go-next"><span class="ls-text">Voltar</span></a>

  <!-- Nome do produto/marca com sidebar -->
    <h1 class="ls-brand-name">
      <a href="home" class="ls-ico-earth">
        <small>Banco - Limpeza</small>
        Gescom Intranet
      </a>
    </h1>

  <!-- Nome do produto/marca sem sidebar quando for o pre-painel  -->
</div>


<aside class="ls-sidebar">
  <div class="ls-sidebar-inner">
      <a href="/financeiro/boleto/gerar"  class="ls-go-prev"><span class="ls-text">Voltar à lista de serviços</span></a>
      <nav class="ls-menu">
        <ul>
           <li><a href="/financeiro/boleto/gerar" class="ls-ico-month" title="Gerar Boletos">Gerar Boletos</a></li>
        </ul>
      </nav>
  </div>
</aside>/


    <main class="ls-main ">
      <div class="container-fluid">
        <h1 class="ls-title-intro ls-ico-month">Banco de Dados - Query</h1>

        
        <?php foreach ($messages as $message): ?>
          <div class="<?php echo $message['status'] ?> ls-dismissable">
            <span data-ls-module="dismiss" class="ls-dismiss">&times;</span>
            <?php echo $message['text'] ?>
          </div>
        <?php endforeach ?>

        <form action="/desenvolvedor/banco/limpeza" method="post" class="ls-form ls-form-inline row">
          <fieldset>
            <label class="ls-label col-md-3">
              <b class="ls-label-text">Data da Limpeza</b>
              <input type="number" name="form[year]" min="1987" max="<?php echo date('Y') ?>" step="1" value="<?php echo $post['form']['year'] ?>">
            </label>
          </fieldset>
          <div class="ls-actions-btn">
            <button class="ls-btn">Executar</button>
          </div>
        </form>

        <?php if ($result > 0): ?>
        <div class="row">
          <div class="col-md-12">
            <h3>Resultados da Query</h3>
            <?php var_dump($result) ?>
          </div>
        </div>
        <?php endif ?>

      </div>
    </main>

    <!-- We recommended use jQuery 1.10 or up -->
    <script type="text/javascript" src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="http://assets.locaweb.com.br/locastyle/3.10.0/javascripts/locastyle.js" type="text/javascript"></script>
  </body>
</html>

