<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<style>
  #simula {
    display: none;
  }

  #image-box {
    background: url(assets/img/img-login.jpg) no-repeat;
    background-size: cover;
    background-position: top;
    height: 100vh;
    width: 37%;
  }

  #image-box #container-logos {
    height: 100%;
    display: flex;
    align-items: flex-end;
    width: 100%;
  }


  #image-box #container-logos img {
    margin: 20px;
  }

  #image-box #container-logos img:last-child {
    margin-bottom: 30px;
  }

  #form-box {
    position: fixed;
    top: 0;
    right: 0;
    height: 100vh;
    width: 63%;
    background: #e6e4d7;

    display: flex;
    align-items: center;
    justify-content: space-between;
    flex-direction: column;
  }

  #form-container {
    width: 546px;
  }

  #form-container .form-image-container {
    display: flex;
    align-items: center;
    justify-content: center;
  }

  #form-container h1 {
    font-style: normal;
    font-weight: 700;
    font-size: 30px;
    line-height: 41px;
    color: #363636;
    text-align: center;
    margin-bottom: 30px;
  }

  #form-container button {
    background: #19790A;
    border-radius: 5px;
    border: none;
    color: #fff;
    font-weight: 700;
    font-size: 16px;
    line-height: 22px;
    padding: 10px 0;
    width: 100%;
  }

  #logo {
    margin-bottom: 10px;
  }

  #logo-butantan {
    margin-top: 25px;
  }

  #form-footer {
    width: 566px;
  }

  #form-footer hr {
    width: 100%;
    border: 1px solid #2F2F2F;
  }

  #desenvolvido-por {
    font-weight: 400;
    font-size: 14px;
    line-height: 164.52%;

    color: #7B7B7B;
  }

  #version {
    font-weight: 400;
    font-size: 14px;
    line-height: 164.52%;

    color: #2F2F2F;
  }

  @media (max-width: 1205px) {
    #form-container {
      width: 70%;
    }

    #form-footer {
      width: 83%;
    }
  }

  @media (max-width: 810px) {
    #image-box {
      display: none;
    }

    #form-box {
      width: 100%;
    }
  }
</style>

<main>
  <div id="login">
    <div id="image-box">
      <div id="container-logos">
      </div>
    </div>

    <div id="form-box" style="overflow-y: auto;">
      <div></div>
      <div id="form-container">


        <?php
        if ($_GET['msg']) { ?>
          <div class=" alert alert-warning ls-dismissable">
            <span data-ls-module="dismiss" class="ls-dismiss">&times;</span>
            <?= $_GET['msg'] ?>
          </div>
        <?php } ?>
        <h4 style="color: #010626">Entrar</h4>
        <p>Use o usuário de rede para acessar o sistema.</p>

        <form method="POST" class="ls-form ls-login-form" action="login/auth">
          <fieldset>
            <label class="ls-label">
              <b class="ls-label-text ls-hidden-accessible">Usuário</b>
              <input class="ls-login-bg-user ls-field-lg" type="text" placeholder="Usuário" required autofocus name="email" oninput="blockAtCharacter(this)">
            </label>

            <label class="ls-label">
              <b class="ls-label-text ls-hidden-accessible">Senha</b>
              <input class="ls-login-bg-password ls-field-lg" type="password" placeholder="Senha" name="password" required autocomplete="off">
            </label>
            <label class="ls-label" id="simula">
              <b class="ls-label-text ls-hidden-accessible">Simula</b>
              <input class="ls-field-lg" type="text" placeholder="Simula" name="simula">
            </label>
            <button type="submit" class="btn btn-primary btn-block btn-lg" style="background-color: #4463b0; border-radius: 10px">Entrar</button>
            <div class="text-center">
              <img src="assets/img/logos.png" width="60%" class="mt-3">
            </div>
          </fieldset>
        </form>
      </div>

      <div id="form-footer">

        <div class="form-image-container text-center">
        </div>
        <hr>
        <p id="desenvolvido-por" class="text-center">Criado por Tic Desenvolvimento<br> Todos os direitos reservados ao <span ondblclick="acessarComo()">©</span> Instituto Butantan 2023</p>
        <p id="version" class="text-center">V0.1 - 26/07/2023 11:42</p>
      </div>
    </div>
  </div>
</main>

<script>
  function blockAtCharacter(inputField) {
    const forbiddenCharacter = '@';
    const currentValue = inputField.value;
    const newValue = currentValue.replace(forbiddenCharacter, '');

    if (currentValue !== newValue) {
      inputField.value = newValue;
    }
  }
</script>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<script>
  function acessarComo() {
    document.getElementById("simula").style.display = 'block';
  }

  $('input[name="usuario"]').keyup(function() {
    $(this).val($(this).val().toLowerCase());
  });
</script>